apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controller
  labels:
    app: helloworld

spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      name: pod3
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: arjunachari12/k8s-demo
        ports:
        - containerPort: 3000