apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mysql
    ports:
      - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: MYSQL_USER
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: MYSQL_PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: MYSQL_DATABASE