apiVersion: v1
kind: Secret
metadata:
  name: helloworld-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXktc2VjcmV0LXB3
  MYSQL_USER: cmF2aQ==
  MYSQL_PASSWORD: cmF2aTEyMw==
  MYSQL_DATABASE: ZGIxMjM=
