apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: helloworld
spec:
  containers:
  - name: myapp
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from Ravi"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    